baseURL = 'https://denismikhalev.dev/'
languageCode = 'en-us'
title = 'Denis Mikhalev'
theme = 'PaperMod'

[params]
    env = "production"
    title = "Denis Mikhalev"
    description = "Personal website of a developer"
    ShowReadingTime = true
    displayFullLangName = true
    ShowShareButtons = true
    defaultTheme = "auto"